language: python
python:
  - "2.7"
services:
  - rabbitmq
install:
  # Build/test dependencies
  - pip install -r requirements.txt --use-mirrors
script:
  - fab test:skip_js=True
after_success:
  coveralls
notifications:
  email:
    - "myer0052@gmail.com"
